export const projects = [
  {
    title: 'Pacman Unity Remake',
    description: "Using Unity, C#, Visual Studio & Google Drive, we are re-creating the aspects of the world of Pac-Man, a 2D single-player game that consists of collecting pellets while avoiding ghosts.",
      image: '/images/pacman.jpg',
      tags: ['Unity', 'C#', 'Visual Studio', 'Google Drive'],
    source: 'https://github.com/BPhi-ai/ACMFallAdvancedProject-Pacman',
    id: 0,
  },
  {
    title: 'Tetris Unity Remake',
    description:"Within the recreation of Tetris, we are implementing some aspects of Unity, C#, Visual Studio & Google Drive to fully implement the game mechanics and sprites.",
    image: '/images/tetris.jpg',
    tags: ['Unity', 'C#', 'Visual Studio', 'Google Drive'],
    source: 'https://github.com/BPhi-ai/ACMSpringAdvancedProject-Tetris',
    id: 1,
  },
  {
    title: 'Bloons Tower Defense Unity Remake',
    description: "This is a remake of the original Bloons Tower Defense game, using Unity API, C#, Visual Studio and Google Drive, in addition of the game mechanics and sprites being provided from the original game.",
      image: '/images/btd.jpg',
      tags: ['Unity', 'C#', 'Visual Studio', 'Google Drive'],
    source: 'https://github.com/BPhi-ai/ACMFallAdvancedProject-BloonsTowerDefense',
    id: 2,
  },
  {
    title: 'Java Local Multiplayer Chess AI',
    description: "A multiplayer chess game that contains some aspects of the Java API documentation, JavaFX, & UI and AI elements to give multiplayer support of chess.",
    image: '/images/chess.png',
    tags: ['Java', 'JavaFX', 'Guava'],
    source: '#null',
    id: 3,
  },
  {
    title: 'ACM@CSULA Website',
    description: "This is a functionally-working website, made for the Association for Computing Machinery team at California State University, Los Angeles. The team is responsible for updating the website for any events and activities that the organization offers to its members.",
    image: '/images/acm.png',
    tags: ['React', 'CSS', 'HTML', 'JavaScript', 'Visual Studio'],
    source: 'https://github.com/BPhi-ai/ACM-Main-Website/tree/master',
    id: 4,
  },
  {
    title: 'Firefox UI Migrator Modal',
    description: "A collaborative capstone project with CSULA and the Mozilla Foundation, consists of updating Firefox's main migratory modal to allow more browsers to be migrated into Firefox, and to allow more resources from existing migrators to be migrated from.",
    image: '/images/mozilla.png',
    tags: ['JavaScript', 'HTML', 'CSS', 'Bugzilla', 'Matrix'],
    source: '#null',
    id: 5,
  },
  {
    title: 'Minecraft 1.19 ACMium Mod',
    description: "This will be a developing mod that will be deployed into Minecraft 1.19 servers, that includes additional blocks, weapons, armor, potions, and much more into the world of Minecraft.",
    image: '/images/minecraft.png',
    tags: ['Java', 'Forge', 'Visual Studio', 'Google Drive'],
    source: 'https://github.com/BPhi-ai/ACMatic_Experience_Mod',
    id: 6,
  },
  {
    title: 'Website Portfolio',
    description: "This project, is the site that you are currently looking at right now! With some aspects of JavaScript and React, we will be developing a dynamic website that will be updated within each project upload.",
    image: '/images/portfolio.png',
    tags: ['React', 'JavaScript', 'CSS', 'HTML', 'Tailwind'],
    source: 'https://github.com/BPhi-ai/Website-Portfolio',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Attended California State University, Los Angeles as a Computer Science Major', },
  { year: 2020, text: 'Worked with multiple Java-based Projects', },
  { year: 2021, text: 'Made multiple Unity-based games based on recreating original games', },
  { year: 2022, text: 'Collaborated with the Mozilla Foundation on August 2022', },
  { year: 2023, text: 'Graduated from California State University, Los Angeles with Cum Laude honors', },
];